#!/bin/sh

set -- `getopt "r:p:vn" "$@"`

PORT=5432
ROOT="./db2"
VERBOSE=""
NOACT=""

while [ ! -z "$1" ]; do
    case "$1" in
        -r) ROOT=$2;;
        -p) PORT=$2;;
        -v) VERBOSE="-d";;
        -n) NOACT="-n";;
    esac
    shift
done

kexecpg $NOACT $VERBOSE -p $PORT $ROOT/create_db.sqlpy
kexecpg $NOACT $VERBOSE -p $PORT $ROOT/create_event_db.sqlpy
kexecpg $NOACT $VERBOSE -p $PORT $ROOT/create_keys_db.sqlpy
kexecpg $NOACT $VERBOSE -p $PORT $ROOT/create_profiles_db.sqlpy
kexecpg $NOACT $VERBOSE -p $PORT $ROOT/create_login_db.sqlpy
kexecpg $NOACT $VERBOSE -p $PORT $ROOT/create_otut_db.sqlpy
